import { GitMerge, KeyRound, ShieldAlert, ShieldCheck, Users } from "lucide-react";

const tone = { awaiting_observations: "text-white/55 border-white/10 bg-white/[0.03]", awaiting_quorum: "text-amber-200 border-amber-300/20 bg-amber-300/[0.05]", quorum_reached: "text-teal-200 border-teal-300/25 bg-teal-300/[0.05]", conflict: "text-red-200 border-red-300/25 bg-red-300/[0.05]" };

export default function FederatedSwarmPanel({ swarm }) {
  if (!swarm) return null;
  const status = swarm.state || "awaiting_observations";
  return <section className={`mx-3 mb-2 rounded-xl border p-3 ${tone[status] || tone.awaiting_observations}`} aria-label="Omega Federated Swarm Intelligence">
    <div className="flex items-start justify-between gap-3"><div className="flex items-center gap-2"><div className="rounded-lg border border-current/20 bg-black/20 p-1.5"><GitMerge className="h-3.5 w-3.5" /></div><div><div className="text-[9px] font-mono uppercase tracking-[0.18em] opacity-70">Federated Swarm</div><div className="text-xs text-white/70">Distributed healing observations</div></div></div><span className="rounded-full border border-current/25 px-2 py-0.5 text-[9px] font-mono uppercase tracking-wider">{status}</span></div>
    <div className="mt-2 grid grid-cols-4 gap-1.5 text-center font-mono text-[9px]"><div className="rounded border border-white/5 bg-black/20 p-1.5"><Users className="mx-auto h-3 w-3 opacity-60" /><div className="mt-0.5 text-white/80">{swarm.quorum || 0}/{swarm.required || 2}</div><div className="opacity-45">quorum</div></div><div className="rounded border border-white/5 bg-black/20 p-1.5"><ShieldCheck className="mx-auto h-3 w-3 opacity-60" /><div className="mt-0.5 text-white/80">{swarm.verified?.length || 0}</div><div className="opacity-45">verified</div></div><div className="rounded border border-white/5 bg-black/20 p-1.5"><ShieldAlert className="mx-auto h-3 w-3 opacity-60" /><div className="mt-0.5 text-white/80">{swarm.rejected?.length || 0}</div><div className="opacity-45">rejected</div></div><div className="rounded border border-white/5 bg-black/20 p-1.5"><KeyRound className="mx-auto h-3 w-3 opacity-60" /><div className="mt-0.5 truncate text-white/80">{swarm.nodeId || "local"}</div><div className="opacity-45">local node</div></div></div>
    <div className="mt-2 text-[9px] leading-relaxed text-white/45">{status === "quorum_reached" ? `Quorum supports ${swarm.proposal}; consequential healing remains Shadow Council gated.` : status === "conflict" ? "Conflicting node proposals require council or operator resolution." : status === "awaiting_quorum" ? `Awaiting one more fresh independent node for ${swarm.proposal || "a registered proposal"}.` : "Local observation boundary active; no distributed consensus claimed."}</div>
  </section>;
}
